package literalpolicy

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestCheckAndFixRepository(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	path := filepath.Join(root, "sample.go")
	source := `package sample

var dense = Config{Name: "example", URL: "https://example.invalid", Enabled: true}
var small = Point{X: 1, Y: 2}
//literalpolicy:allow aliases are grouped by canonical value
var grouped = Config{Name: "example", URL: "https://example.invalid", Enabled: true}
var mixed = Config{
	Name: "example", URL: "https://example.invalid",
	Enabled: true}
`
	if err := os.WriteFile(path, []byte(source), 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	violations, err := CheckRepository(root)
	if err != nil {
		t.Fatalf("check fixture: %v", err)
	}
	if len(violations) != 2 {
		t.Fatalf("violation count = %d, want 2", len(violations))
	}
	if fixed, err := FixRepository(root); err != nil || fixed != 1 {
		t.Fatalf("FixRepository() = (%d, %v), want (1, nil)", fixed, err)
	}
	violations, err = CheckRepository(root)
	if err != nil {
		t.Fatalf("recheck fixture: %v", err)
	}
	if len(violations) != 0 {
		t.Fatalf("remaining violations = %d, want 0", len(violations))
	}
	updated, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if !strings.Contains(string(updated), `var small = Point{X: 1, Y: 2}`) {
		t.Fatal("two-element literal was unexpectedly expanded")
	}
	if !strings.Contains(string(updated), `var grouped = Config{Name: "example", URL: "https://example.invalid", Enabled: true}`) {
		t.Fatal("allowed literal was unexpectedly expanded")
	}
}

func TestGeneratedFileIsIgnored(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	source := "// Code generated by test. DO NOT EDIT.\npackage sample\nvar value = T{A: 1, B: 2, C: 3}\n"
	if err := os.WriteFile(filepath.Join(root, "generated.go"), []byte(source), 0o600); err != nil {
		t.Fatalf("write fixture: %v", err)
	}
	violations, err := CheckRepository(root)
	if err != nil {
		t.Fatalf("check fixture: %v", err)
	}
	if len(violations) != 0 {
		t.Fatalf("generated violations = %d, want 0", len(violations))
	}
}
